
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ismael
 */
public class panelControlUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form panelInicio
     */
    public panelControlUsuarios() {
        initComponents();
        cargarDatos();
    }

    private void cargarDatos(){
        try{
            //Conexión a la BD
            Class.forName("org.postgresql.Driver");
            Connection con = (Connection)DriverManager.getConnection(
            "jdbc:postgresql://localhost/INAH","postgres","inah");
            Statement sentencia = con.createStatement();
            Statement sentenciaU = con.createStatement();
            Statement sentenciaA = con.createStatement();
           
            //Llenar el combobox de area a seleccionar
            ResultSet documento = sentencia.executeQuery("SELECT * FROM area");
            while(documento.next()){
                cmbArea.addItem(documento.getString("nombre_area"));
            }
           
            //Llenar tabla con usuarios existentes
            DefaultTableModel modelo = null;
            String Titulo[]={"Nombre","Ap. paterno", "Ap. materno", "Estudios", 
                "Correo","Teléfono", "Tipo Usuario", "Usuario", "Contraseña", "Area"};
            modelo= new DefaultTableModel(null,Titulo);
            String registro[]=new String[10];
            int idArea, idPersonal;
            ResultSet personal = sentencia.executeQuery("SELECT * FROM personal");
            while(personal.next()){
                //llena la parte de personal
                registro[0] = personal.getString("nombre");
                registro[1] = personal.getString("apellido_paterno");
                registro[2] = personal.getString("apellido_materno");
                registro[3] = personal.getString("estudios");
                registro[4] = personal.getString("correo_institucional");
                registro[5] = personal.getString("telefono");
                idArea = personal.getInt("idarea");
                idPersonal = personal.getInt("idpersonal");
                
                //llena la parte de usuarios
                ResultSet usuarios = sentenciaU.executeQuery("SELECT * FROM usuarios WHERE idpersonal = " + idPersonal);
                while(usuarios.next()){
                    registro[6] = usuarios.getString("tipo_usuario");
                    registro[7] = usuarios.getString("usuario");
                    registro[8] = usuarios.getString("contraseña");
                }
                
                //llena la parte de area
                ResultSet area = sentenciaA.executeQuery("SELECT * FROM area WHERE idarea = " + idArea);
                while(area.next()){
                    registro[9] = area.getString("nombre_area");
                }
                modelo.addRow(registro);
            }
            tblUsuarios.setModel(modelo);
      }
      catch(ClassNotFoundException | SQLException e){
             e.printStackTrace();
         }//fin del catch
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApPaterno = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        lblApMaterno = new javax.swing.JLabel();
        txtApMaterno = new javax.swing.JTextField();
        lblEstudios = new javax.swing.JLabel();
        cmbEstudios = new javax.swing.JComboBox<>();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblEstudios1 = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        pnlUsuariosINAH = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblContra = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        cmbArea = new javax.swing.JComboBox<>();
        pnlGuardar = new javax.swing.JPanel();
        lblGuardar = new javax.swing.JLabel();
        pnlGuardar1 = new javax.swing.JPanel();
        lblGuardar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ap. paterno", "Ap. materno", "Estudios", "Correo", "Telefono", "Tipo de usuario", "Usuario", "Contraseña", "Área"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 880, 260));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre(s):");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 140, -1));

        lblApPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblApPaterno.setText("Ap. paterno:");
        jPanel1.add(lblApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        txtApPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApPaternoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 140, -1));

        lblApMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblApMaterno.setText("Ap. materno:");
        jPanel1.add(lblApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        txtApMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApMaternoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 140, -1));

        lblEstudios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstudios.setText("Estudios:");
        jPanel1.add(lblEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        cmbEstudios.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbEstudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Preescolar", "Primaria", "Secundaria", "Bachillerato", "Licenciatura en Arquitectura", "Maestría", "Doctorado" }));
        cmbEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstudiosActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 150, -1));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCorreo.setText("Correo:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 170, -1));

        lblNombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre1.setText("Teléfono:");
        jPanel1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 100, -1));

        lblEstudios1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstudios1.setText("Tipo de usuario:");
        jPanel1.add(lblEstudios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        cmbTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Ciudadano", "Restaurador", "Arquitecto", "Operador", "Delegado", " " }));
        cmbTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 150, -1));

        pnlUsuariosINAH.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsuariosINAH.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios INAH", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlUsuariosINAH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreUsuario.setText("Nombre Usuario:");
        pnlUsuariosINAH.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        pnlUsuariosINAH.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 140, -1));

        lblContra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContra.setText("Contraseña:");
        pnlUsuariosINAH.add(lblContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        pnlUsuariosINAH.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, -1));

        lblArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArea.setText("Área:");
        pnlUsuariosINAH.add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        cmbArea.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", " " }));
        cmbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaActionPerformed(evt);
            }
        });
        pnlUsuariosINAH.add(cmbArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 150, -1));

        jPanel1.add(pnlUsuariosINAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 510, 120));

        pnlGuardar.setBackground(new java.awt.Color(76, 145, 65));
        pnlGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGuardarMouseClicked(evt);
            }
        });

        lblGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(255, 255, 255));
        lblGuardar.setText("Guardar");
        lblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlGuardarLayout = new javax.swing.GroupLayout(pnlGuardar);
        pnlGuardar.setLayout(pnlGuardarLayout);
        pnlGuardarLayout.setHorizontalGroup(
            pnlGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGuardarLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(lblGuardar)
                .addGap(59, 59, 59))
        );
        pnlGuardarLayout.setVerticalGroup(
            pnlGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 190, -1));

        pnlGuardar1.setBackground(new java.awt.Color(155, 17, 30));
        pnlGuardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGuardar1MouseClicked(evt);
            }
        });

        lblGuardar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        lblGuardar1.setText("Eliminar");
        lblGuardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlGuardar1Layout = new javax.swing.GroupLayout(pnlGuardar1);
        pnlGuardar1.setLayout(pnlGuardar1Layout);
        pnlGuardar1Layout.setHorizontalGroup(
            pnlGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGuardar1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(lblGuardar1)
                .addGap(59, 59, 59))
        );
        pnlGuardar1Layout.setVerticalGroup(
            pnlGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuardar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuardar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApPaternoActionPerformed

    private void txtApMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApMaternoActionPerformed

    private void cmbEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstudiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstudiosActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void cmbTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoUsuarioActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void cmbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAreaActionPerformed

    private void lblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseClicked
        guardarModificar();
    }//GEN-LAST:event_lblGuardarMouseClicked

    private void pnlGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGuardarMouseClicked
        guardarModificar();
    }//GEN-LAST:event_pnlGuardarMouseClicked

    private void lblGuardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGuardar1MouseClicked

    private void pnlGuardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGuardar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlGuardar1MouseClicked

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void guardarModificar(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbArea;
    private javax.swing.JComboBox<String> cmbEstudios;
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApMaterno;
    private javax.swing.JLabel lblApPaterno;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEstudios;
    private javax.swing.JLabel lblEstudios1;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblGuardar1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JPanel pnlGuardar;
    private javax.swing.JPanel pnlGuardar1;
    private javax.swing.JPanel pnlUsuariosINAH;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
